### ISSUE TITLE
iBuffalo measurements

### ISSUE THREAD

**Issue by James-F2** [eniva/MisSTer_Guides#1]
One of the fastest controllers.

![ibuffalo](https://user-images.githubusercontent.com/31185814/71338257-d5f1d680-2557-11ea-9e34-4b66dabc3234.png)

**Comment by eniva** [comment]
Thank you, I love this controller!
I added it to the wiki.

I also noticed you have a DualShock 4. I've been told someone found out that it's forced to 4ms.
I'll try to cram a release that adds DualShock 4 support for custom poll rates before Christmas.
